export const eventCategories = [
  { id: 1, name: "All Events", color: "#002fa7" },
  { id: 2, name: "Conferences", color: "#0066cc" },
  { id: 3, name: "Workshops", color: "#047857" },
  { id: 4, name: "Networking", color: "#7c3aed" },
  { id: 5, name: "Webinars", color: "#dc2626" },
  { id: 6, name: "Career Fairs", color: "#ea580c" },
];

export const events = [
  {
    id: 1,
    title: "Africa Tech Summit 2024",
    category: "Conferences",
    date: "March 15-17, 2024",
    location: "Yaoundé Conference Center",
    excerpt: "Join 500+ tech leaders, investors, and innovators for three days of insights, networking, and innovation.",
    image: "/src/assets/latest-news/g20-sumit.png",
    price: "Free",
    status: "Upcoming",
    organizer: "Tech Hub Africa"
  },
  {
    id: 2,
    title: "Digital Marketing Masterclass",
    category: "Workshops",
    date: "March 20, 2024",
    location: "Douala Business Center",
    excerpt: "Learn cutting-edge digital marketing strategies from industry experts in this intensive one-day workshop.",
    image: "/src/assets/latest-news/g20-sumit.png",
    price: "15,000 FCFA",
    status: "Upcoming",
    organizer: "Marketing Pro Academy"
  },
  {
    id: 3,
    title: "Startup Founders Meetup",
    category: "Networking",
    date: "March 22, 2024",
    location: "Impact Hub Bamenda",
    excerpt: "Connect with fellow entrepreneurs, share experiences, and build valuable partnerships.",
    image: "/src/assets/latest-news/g20-sumit.png",
    price: "Free",
    status: "Upcoming",
    organizer: "Startup Cameroon"
  },
  {
    id: 4,
    title: "AI & Machine Learning Webinar",
    category: "Webinars",
    date: "March 25, 2024",
    location: "Online",
    excerpt: "Explore the latest trends in artificial intelligence and machine learning applications.",
    image: "/src/assets/latest-news/g20-sumit.png",
    price: "Free",
    status: "Upcoming",
    organizer: "AI Institute"
  },
  {
    id: 5,
    title: "Graduate Employment Fair 2024",
    category: "Career Fairs",
    date: "April 5, 2024",
    location: "University of Buea",
    excerpt: "Meet top employers, submit your CV, and discover exciting career opportunities across various sectors.",
    image: "/src/assets/latest-news/g20-sumit.png",
    price: "Free",
    status: "Upcoming",
    organizer: "Ministry of Employment"
  },
  {
    id: 6,
    title: "Women in Tech Conference",
    category: "Conferences",
    date: "April 10-11, 2024",
    location: "Kribi Resort & Conference Hall",
    excerpt: "Empowering women in technology through mentorship, skill-building, and networking opportunities.",
    image: "/src/assets/latest-news/g20-sumit.png",
    price: "20,000 FCFA",
    status: "Upcoming",
    organizer: "Women Tech Network"
  },
  {
    id: 7,
    title: "Financial Literacy Workshop",
    category: "Workshops",
    date: "April 15, 2024",
    location: "Garoua Community Center",
    excerpt: "Master personal finance, investment strategies, and wealth-building techniques.",
    image: "/src/assets/latest-news/g20-sumit.png",
    price: "10,000 FCFA",
    status: "Upcoming",
    organizer: "Finance Academy"
  },
  {
    id: 8,
    title: "Creative Industries Networking Night",
    category: "Networking",
    date: "April 18, 2024",
    location: "Limbe Arts Center",
    excerpt: "Connect with artists, designers, filmmakers, and creative professionals.",
    image: "/src/assets/latest-news/g20-sumit.png",
    price: "5,000 FCFA",
    status: "Upcoming",
    organizer: "Creative Cameroon"
  },
  {
    id: 9,
    title: "Cybersecurity Essentials Webinar",
    category: "Webinars",
    date: "April 22, 2024",
    location: "Online",
    excerpt: "Learn how to protect your business and personal data from cyber threats.",
    image: "/src/assets/latest-news/g20-sumit.png",
    price: "Free",
    status: "Upcoming",
    organizer: "CyberSafe Africa"
  },
  {
    id: 10,
    title: "International Job Fair",
    category: "Career Fairs",
    date: "May 3, 2024",
    location: "Yaoundé Hilton",
    excerpt: "Explore international career opportunities with multinational companies and NGOs.",
    image: "/src/assets/latest-news/g20-sumit.png",
    price: "Free",
    status: "Upcoming",
    organizer: "Global Careers Network"
  },
  {
    id: 11,
    title: "Blockchain & Cryptocurrency Summit",
    category: "Conferences",
    date: "May 8-9, 2024",
    location: "Douala Marriott",
    excerpt: "Discover the future of finance with blockchain technology and digital currencies.",
    image: "/src/assets/latest-news/g20-sumit.png",
    price: "25,000 FCFA",
    status: "Upcoming",
    organizer: "Crypto Africa"
  },
  {
    id: 12,
    title: "Public Speaking Masterclass",
    category: "Workshops",
    date: "May 12, 2024",
    location: "Bafoussam Training Center",
    excerpt: "Develop confidence and skills to deliver powerful presentations and speeches.",
    image: "/src/assets/latest-news/g20-sumit.png",
    price: "12,000 FCFA",
    status: "Upcoming",
    organizer: "Speakers Academy"
  },
];
