export const newsArticles = [
  {
    id: 1,
    category: "Politics",
    title: "Government Announces New Infrastructure Development Plan",
    excerpt: "Major cities to benefit from comprehensive road and transportation upgrades in the coming fiscal year.",
    author: "Sarah Johnson",
    timestamp: "2 hours ago",
    image: "/assets/latest-news/g20-sumit.png",
    featured: true,
  },
  {
    id: 2,
    category: "Business",
    title: "Tech Startups See Record Investment Growth",
    excerpt: "Local entrepreneurs attract international funding as innovation sector expands.",
    author: "Michael Chen",
    timestamp: "4 hours ago",
    image: "/assets/latest-news/g20-sumit.png",
    trending: true,
  },
  {
    id: 3,
    category: "Entertainment",
    title: "Film Festival Announces Award Winners",
    excerpt: "Celebrating excellence in cinema with groundbreaking performances.",
    author: "Emma Williams",
    timestamp: "5 hours ago",
    image: "/assets/latest-news/g20-sumit.png",
    trending: true,
  },
  {
    id: 4,
    category: "International",
    title: "Climate Summit Reaches Breakthrough Agreement",
    excerpt: "Nations commit to ambitious carbon reduction targets.",
    author: "David Martinez",
    timestamp: "6 hours ago",
    image: "/assets/latest-news/g20-sumit.png",
    trending: true,
  },
  {
    id: 5,
    category: "Business",
    title: "Stock Markets Rally on Economic Data",
    excerpt: "Positive indicators drive investor confidence across sectors.",
    author: "Lisa Anderson",
    timestamp: "7 hours ago",
    image: "/assets/latest-news/g20-sumit.png",
    trending: true,
  },
  {
    id: 6,
    category: "Politics",
    title: "Legislative Reform Package Passes Parliament",
    excerpt: "Sweeping changes to governance structure approved after months of debate.",
    author: "Robert Taylor",
    timestamp: "8 hours ago",
    image: "/assets/latest-news/g20-sumit.png",
  },
  {
    id: 7,
    category: "International",
    title: "Trade Agreement Signed Between Major Economies",
    excerpt: "Historic deal promises to boost cross-border commerce and cooperation.",
    author: "Jennifer Lee",
    timestamp: "9 hours ago",
    image: "/assets/latest-news/g20-sumit.png",
  },
  {
    id: 8,
    category: "Entertainment",
    title: "Music Awards Celebrate Diverse Talent",
    excerpt: "Industry honors breakthrough artists and legendary performers.",
    author: "Chris Brown",
    timestamp: "10 hours ago",
    image: "/assets/latest-news/g20-sumit.png",
  },
  {
    id: 9,
    category: "Business",
    title: "Renewable Energy Sector Attracts Major Investment",
    excerpt: "Green technology companies secure funding for expansion projects.",
    author: "Amanda White",
    timestamp: "11 hours ago",
    image: "/assets/latest-news/g20-sumit.png",
  },
  {
    id: 10,
    category: "International",
    title: "Humanitarian Aid Reaches Crisis Region",
    excerpt: "International organizations coordinate relief efforts for affected populations.",
    author: "Daniel Kim",
    timestamp: "12 hours ago",
    image: "/assets/latest-news/g20-sumit.png",
  },
];

export const categories = [
  { name: "Latest", color: "#002fa7" },
  { name: "International", color: "#0066cc" },
  { name: "Business", color: "#047857" },
  { name: "Entertainment", color: "#7c3aed" },
  { name: "Politics", color: "#dc2626" },
];
