export const opportunityCategories = [
  { id: 1, name: "All Opportunities", color: "#002fa7" },
  { id: 2, name: "Jobs", color: "#0066cc" },
  { id: 3, name: "Internships", color: "#047857" },
  { id: 4, name: "Fellowships", color: "#7c3aed" },
  { id: 5, name: "Volunteering", color: "#dc2626" },
  { id: 6, name: "Grants", color: "#ea580c" },
];

export const opportunities = [
  {
    id: 1,
    title: "Software Engineer - Full Stack",
    category: "Jobs",
    company: "Tech Solutions Africa",
    location: "Douala, Cameroon",
    type: "Full-time",
    excerpt: "Join our dynamic team to build innovative web applications using modern technologies. 3+ years experience required.",
    image: "/src/assets/latest-news/g20-sumit.png",
    salary: "Competitive",
    deadline: "March 30, 2024",
    experience: "3+ years"
  },
  {
    id: 2,
    title: "Marketing Intern",
    category: "Internships",
    company: "Digital Marketing Hub",
    location: "Yaoundé, Cameroon",
    type: "Internship",
    excerpt: "6-month paid internship opportunity to learn digital marketing strategies and campaign management.",
    image: "/src/assets/latest-news/g20-sumit.png",
    salary: "150,000 FCFA/month",
    deadline: "April 5, 2024",
    experience: "Entry Level"
  },
  {
    id: 3,
    title: "African Leadership Fellowship Program",
    category: "Fellowships",
    company: "Leadership Institute",
    location: "Pan-African",
    type: "Fellowship",
    excerpt: "12-month leadership development program for emerging African leaders with mentorship and networking.",
    image: "/src/assets/latest-news/g20-sumit.png",
    salary: "Fully Funded",
    deadline: "April 15, 2024",
    experience: "2+ years"
  },
  {
    id: 4,
    title: "Community Health Volunteer",
    category: "Volunteering",
    company: "Health for All NGO",
    location: "Bamenda, Cameroon",
    type: "Volunteer",
    excerpt: "Support community health initiatives and awareness campaigns in rural areas. Training provided.",
    image: "/src/assets/latest-news/g20-sumit.png",
    salary: "Volunteer",
    deadline: "Rolling",
    experience: "No experience"
  },
  {
    id: 5,
    title: "Small Business Development Grant",
    category: "Grants",
    company: "Entrepreneurship Fund",
    location: "Cameroon",
    type: "Grant",
    excerpt: "Up to 5 million FCFA in funding for innovative small business ideas in technology and agriculture.",
    image: "/src/assets/latest-news/g20-sumit.png",
    salary: "Up to 5M FCFA",
    deadline: "May 1, 2024",
    experience: "Business Plan Required"
  },
  {
    id: 6,
    title: "Data Analyst",
    category: "Jobs",
    company: "Analytics Pro",
    location: "Remote",
    type: "Remote",
    excerpt: "Analyze business data and create insights using Python, SQL, and visualization tools.",
    image: "/src/assets/latest-news/g20-sumit.png",
    salary: "400,000 - 600,000 FCFA",
    deadline: "April 10, 2024",
    experience: "2+ years"
  },
  {
    id: 7,
    title: "Graphic Design Intern",
    category: "Internships",
    company: "Creative Studio",
    location: "Limbe, Cameroon",
    type: "Internship",
    excerpt: "Learn professional graphic design and branding in a fast-paced creative environment.",
    image: "/src/assets/latest-news/g20-sumit.png",
    salary: "100,000 FCFA/month",
    deadline: "April 20, 2024",
    experience: "Portfolio Required"
  },
  {
    id: 8,
    title: "Research Fellowship in Climate Change",
    category: "Fellowships",
    company: "Environmental Research Center",
    location: "Buea, Cameroon",
    type: "Fellowship",
    excerpt: "Conduct research on climate adaptation strategies in Central Africa. PhD candidates preferred.",
    image: "/src/assets/latest-news/g20-sumit.png",
    salary: "Stipend Provided",
    deadline: "May 5, 2024",
    experience: "Graduate Level"
  },
  {
    id: 9,
    title: "Education Volunteer Program",
    category: "Volunteering",
    company: "Teach Africa Initiative",
    location: "Various Locations",
    type: "Volunteer",
    excerpt: "Teach English and STEM subjects in underserved communities across Cameroon.",
    image: "/src/assets/latest-news/g20-sumit.png",
    salary: "Volunteer",
    deadline: "Rolling",
    experience: "Teaching Experience Preferred"
  },
  {
    id: 10,
    title: "Women in Tech Innovation Grant",
    category: "Grants",
    company: "Tech Women Fund",
    location: "Cameroon",
    type: "Grant",
    excerpt: "Funding for women-led technology startups and innovation projects. Up to 3 million FCFA.",
    image: "/src/assets/latest-news/g20-sumit.png",
    salary: "Up to 3M FCFA",
    deadline: "April 25, 2024",
    experience: "Women Entrepreneurs"
  },
  {
    id: 11,
    title: "Project Manager",
    category: "Jobs",
    company: "Development Partners",
    location: "Garoua, Cameroon",
    type: "Full-time",
    excerpt: "Lead development projects in infrastructure and community empowerment. PMP certification preferred.",
    image: "/src/assets/latest-news/g20-sumit.png",
    salary: "Competitive Package",
    deadline: "May 10, 2024",
    experience: "5+ years"
  },
  {
    id: 12,
    title: "Content Writing Internship",
    category: "Internships",
    company: "Media House",
    location: "Douala, Cameroon",
    type: "Internship",
    excerpt: "Create engaging content for digital platforms. Strong writing skills and creativity required.",
    image: "/src/assets/latest-news/g20-sumit.png",
    salary: "120,000 FCFA/month",
    deadline: "April 30, 2024",
    experience: "Writing Samples Required"
  },
];
