export const scholarshipCategories = [
  { id: 1, name: "All Scholarships", color: "#002fa7" },
  { id: 2, name: "Undergraduate", color: "#0066cc" },
  { id: 3, name: "Graduate", color: "#047857" },
  { id: 4, name: "PhD", color: "#7c3aed" },
  { id: 5, name: "Short Courses", color: "#dc2626" },
  { id: 6, name: "Research Grants", color: "#ea580c" },
];

export const scholarships = [
  {
    id: 1,
    title: "Mastercard Foundation Scholars Program",
    category: "Undergraduate",
    deadline: "April 30, 2024",
    provider: "Mastercard Foundation",
    location: "Various African Universities",
    excerpt: "Full scholarship covering tuition, accommodation, and living expenses for academically talented students from disadvantaged backgrounds.",
    image: "/src/assets/latest-news/g20-sumit.png",
    amount: "Full Funding",
    level: "Bachelor's Degree",
    field: "All Fields"
  },
  {
    id: 2,
    title: "African Union Commission Scholarship",
    category: "Graduate",
    deadline: "May 15, 2024",
    provider: "African Union",
    location: "Pan-African Universities",
    excerpt: "Fully-funded master's degree scholarships for African students in STEM, agriculture, and health sciences.",
    image: "/src/assets/latest-news/g20-sumit.png",
    amount: "Full Funding",
    level: "Master's Degree",
    field: "STEM, Agriculture, Health"
  },
  {
    id: 3,
    title: "Commonwealth PhD Scholarships",
    category: "PhD",
    deadline: "June 1, 2024",
    provider: "Commonwealth Scholarship Commission",
    location: "UK Universities",
    excerpt: "Doctoral scholarships for students from Commonwealth countries pursuing research in development-related fields.",
    image: "/src/assets/latest-news/g20-sumit.png",
    amount: "Full Funding + Stipend",
    level: "PhD",
    field: "Development Studies"
  },
  {
    id: 4,
    title: "Google Africa Developer Scholarship",
    category: "Short Courses",
    deadline: "April 20, 2024",
    provider: "Google",
    location: "Online",
    excerpt: "Free online training in Android, Web, and Cloud development with certification opportunities.",
    image: "/src/assets/latest-news/g20-sumit.png",
    amount: "Free",
    level: "Certificate",
    field: "Technology"
  },
  {
    id: 5,
    title: "World Bank Graduate Scholarship Program",
    category: "Graduate",
    deadline: "May 30, 2024",
    provider: "World Bank",
    location: "Partner Universities Worldwide",
    excerpt: "Scholarships for master's studies in development-related fields for students from developing countries.",
    image: "/src/assets/latest-news/g20-sumit.png",
    amount: "Full Funding",
    level: "Master's Degree",
    field: "Development, Economics"
  },
  {
    id: 6,
    title: "DAAD Research Grants for Doctoral Students",
    category: "Research Grants",
    deadline: "June 15, 2024",
    provider: "DAAD Germany",
    location: "German Universities",
    excerpt: "Research grants for doctoral candidates and young academics from developing countries.",
    image: "/src/assets/latest-news/g20-sumit.png",
    amount: "€1,200/month",
    level: "PhD Research",
    field: "All Fields"
  },
  {
    id: 7,
    title: "Chevening Scholarships",
    category: "Graduate",
    deadline: "July 1, 2024",
    provider: "UK Government",
    location: "UK Universities",
    excerpt: "Prestigious fully-funded master's scholarships for future leaders and influencers.",
    image: "/src/assets/latest-news/g20-sumit.png",
    amount: "Full Funding",
    level: "Master's Degree",
    field: "All Fields"
  },
  {
    id: 8,
    title: "Erasmus Mundus Joint Master Degrees",
    category: "Graduate",
    deadline: "May 10, 2024",
    provider: "European Commission",
    location: "European Universities",
    excerpt: "Study in multiple European countries with full scholarships covering tuition and living costs.",
    image: "/src/assets/latest-news/g20-sumit.png",
    amount: "€1,400/month + Tuition",
    level: "Master's Degree",
    field: "Various Fields"
  },
  {
    id: 9,
    title: "Fulbright Foreign Student Program",
    category: "Graduate",
    deadline: "June 20, 2024",
    provider: "US Department of State",
    location: "US Universities",
    excerpt: "Graduate study opportunities in the United States for international students.",
    image: "/src/assets/latest-news/g20-sumit.png",
    amount: "Full Funding",
    level: "Master's/PhD",
    field: "All Fields"
  },
  {
    id: 10,
    title: "African Women in STEM Scholarship",
    category: "Undergraduate",
    deadline: "April 25, 2024",
    provider: "STEM Africa Foundation",
    location: "African Universities",
    excerpt: "Scholarships specifically for young African women pursuing STEM education.",
    image: "/src/assets/latest-news/g20-sumit.png",
    amount: "Partial to Full Funding",
    level: "Bachelor's Degree",
    field: "STEM"
  },
  {
    id: 11,
    title: "UNESCO-L'Oréal For Women in Science",
    category: "Research Grants",
    deadline: "May 5, 2024",
    provider: "UNESCO & L'Oréal",
    location: "International",
    excerpt: "Research grants for women scientists pursuing careers in life sciences.",
    image: "/src/assets/latest-news/g20-sumit.png",
    amount: "€15,000 - €20,000",
    level: "PhD/Postdoc",
    field: "Life Sciences"
  },
  {
    id: 12,
    title: "Microsoft Learn Student Ambassadors",
    category: "Short Courses",
    deadline: "Rolling Admission",
    provider: "Microsoft",
    location: "Online",
    excerpt: "Free access to Microsoft certifications, training, and global community of student leaders.",
    image: "/src/assets/latest-news/g20-sumit.png",
    amount: "Free + Benefits",
    level: "Certificate",
    field: "Technology"
  },
];
